# Generated by Django 4.0.10 on 2023-08-24 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector_name', models.CharField(choices=[('Agriculture', 'Agriculture'), ('Manufacturing', 'Manufacturing')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Borrower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrower_name', models.CharField(max_length=50)),
                ('borrower_class', models.CharField(choices=[('Retail', 'Retail'), ('Business', 'Business'), ('Corporate', 'Corporate')], default='', max_length=100)),
                ('LAF_NO', models.CharField(max_length=100)),
                ('Loan_code', models.CharField(max_length=100)),
                ('borrower_branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.branch')),
                ('borrower_sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.sector')),
            ],
        ),
    ]
