# Generated by Django 4.0.10 on 2023-08-24 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QualityOfFinancialStatements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_exposure', models.CharField(choices=[('Greater than or equal to 1 million', 'Greater than or equal to 1 million'), ('Less than 1 million', 'Less than 1 million')], max_length=100)),
                ('score', models.PositiveIntegerField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='FinancialRiskParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector', models.CharField(choices=[('Agriculture', 'Agriculture'), ('Manufacturing', 'Manufacturing'), ('Leather', 'Leather'), ('Export', 'Export'), ('Construction', 'Construction'), ('DTS', 'DTS'), ('Import', 'Import'), ('Others', 'Others')], max_length=100)),
                ('measurement', models.CharField(choices=[('Leverage Ratio', 'Leverage Ratio'), ('Liquidity Ratio', 'Liquidity Ratio'), ('Profitability Ratio', 'Profitability Ratio'), ('Debt Service Coverage Ratio', 'Debt Service Coverage Ratio')], max_length=100)),
                ('min_value', models.DecimalField(decimal_places=2, max_digits=5)),
                ('max_value', models.DecimalField(decimal_places=2, max_digits=5)),
                ('score', models.PositiveIntegerField()),
            ],
            options={
                'unique_together': {('sector', 'measurement', 'min_value', 'max_value')},
            },
        ),
    ]
