# Generated by Django 4.0.10 on 2023-08-19 17:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Borrower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrower_name', models.CharField(max_length=50)),
                ('borrower_class', models.CharField(choices=[('Retail', 'Retail'), ('Business', 'Business'), ('Corporate', 'Corporate')], default='', max_length=100)),
                ('LAF_NO', models.CharField(max_length=100)),
                ('Loan_code', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProfitabilityRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('range_1_upper_bound', models.FloatField()),
                ('range_1_lower_bound', models.FloatField()),
                ('range_1_score', models.PositiveIntegerField()),
                ('range_2_upper_bound', models.FloatField()),
                ('range_2_lower_bound', models.FloatField()),
                ('range_2_score', models.PositiveIntegerField()),
                ('range_3_upper_bound', models.FloatField()),
                ('range_3_lower_bound', models.FloatField()),
                ('range_3_score', models.PositiveIntegerField()),
                ('range_4_upper_bound', models.FloatField()),
                ('range_4_lower_bound', models.FloatField()),
                ('range_4_score', models.PositiveIntegerField()),
                ('range_5_upper_bound', models.FloatField()),
                ('range_5_lower_bound', models.FloatField()),
                ('range_5_score', models.PositiveIntegerField()),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rating.sector')),
            ],
        ),
        migrations.CreateModel(
            name='LiquidityRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('range_1_upper_bound', models.FloatField()),
                ('range_1_lower_bound', models.FloatField()),
                ('range_1_score', models.PositiveIntegerField()),
                ('range_2_upper_bound', models.FloatField()),
                ('range_2_lower_bound', models.FloatField()),
                ('range_2_score', models.PositiveIntegerField()),
                ('range_3_upper_bound', models.FloatField()),
                ('range_3_lower_bound', models.FloatField()),
                ('range_3_score', models.PositiveIntegerField()),
                ('range_4_upper_bound', models.FloatField()),
                ('range_4_lower_bound', models.FloatField()),
                ('range_4_score', models.PositiveIntegerField()),
                ('range_5_upper_bound', models.FloatField()),
                ('range_5_lower_bound', models.FloatField()),
                ('range_5_score', models.PositiveIntegerField()),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rating.sector')),
            ],
        ),
        migrations.CreateModel(
            name='LeverageRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('range_1_upper_bound', models.FloatField()),
                ('range_1_lower_bound', models.FloatField()),
                ('range_1_score', models.PositiveIntegerField()),
                ('range_2_upper_bound', models.FloatField()),
                ('range_2_lower_bound', models.FloatField()),
                ('range_2_score', models.PositiveIntegerField()),
                ('range_3_upper_bound', models.FloatField()),
                ('range_3_lower_bound', models.FloatField()),
                ('range_3_score', models.PositiveIntegerField()),
                ('range_4_upper_bound', models.FloatField()),
                ('range_4_lower_bound', models.FloatField()),
                ('range_4_score', models.PositiveIntegerField()),
                ('range_5_upper_bound', models.FloatField()),
                ('range_5_lower_bound', models.FloatField()),
                ('range_5_score', models.PositiveIntegerField()),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rating.sector')),
            ],
        ),
        migrations.CreateModel(
            name='Financial_stmt_quality_Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audit_type', models.CharField(choices=[('Audited', 'Audited Financial Statement'), ('Provisional', 'Provisional Financial Statement'), ('CommercialReport', 'Commercial Credit Report')], max_length=50)),
                ('audit_discrepancy', models.CharField(choices=[('None', 'No Discrepancy'), ('Major', 'Major Discrepancy'), ('Minor', 'Minor Discrepancy')], max_length=50)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rating.borrower')),
            ],
        ),
        migrations.CreateModel(
            name='Debt_service_coverage_ratio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('range_1_upper_bound', models.FloatField()),
                ('range_1_lower_bound', models.FloatField()),
                ('range_1_score', models.PositiveIntegerField()),
                ('range_2_upper_bound', models.FloatField()),
                ('range_2_lower_bound', models.FloatField()),
                ('range_2_score', models.PositiveIntegerField()),
                ('range_3_upper_bound', models.FloatField()),
                ('range_3_lower_bound', models.FloatField()),
                ('range_3_score', models.PositiveIntegerField()),
                ('range_4_upper_bound', models.FloatField()),
                ('range_4_lower_bound', models.FloatField()),
                ('range_4_score', models.PositiveIntegerField()),
                ('range_5_upper_bound', models.FloatField()),
                ('range_5_lower_bound', models.FloatField()),
                ('range_5_score', models.PositiveIntegerField()),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rating.sector')),
            ],
        ),
        migrations.CreateModel(
            name='CreditRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liquidity_ratio', models.FloatField()),
                ('leverage_ratio', models.FloatField()),
                ('profitability_ratio', models.FloatField()),
                ('debt_service_coverage_ratio', models.FloatField()),
                ('financial_risk', models.PositiveIntegerField(default=0)),
                ('checker', models.ForeignKey(blank=True, limit_choices_to={'role': 'checker'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='checker_ratings', to=settings.AUTH_USER_MODEL)),
                ('financial_stmt_quality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rating.financial_stmt_quality_rating')),
                ('maker', models.ForeignKey(limit_choices_to={'role': 'maker'}, on_delete=django.db.models.deletion.CASCADE, related_name='maker_ratings', to=settings.AUTH_USER_MODEL)),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rating.sector')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='borrower',
            name='borrower_branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rating.branch'),
        ),
        migrations.AddField(
            model_name='borrower',
            name='borrower_sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rating.sector'),
        ),
    ]
