# Generated by Django 4.0.10 on 2023-08-28 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0002_creditanalyst_loantype_loan_creditdecision'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessRiskParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('industry_outlook', models.CharField(choices=[('Favorable', 'Favorable'), ('Stable', 'stable'), ('unstable', 'unstable')], max_length=100)),
                ('score', models.PositiveIntegerField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MarketRiskParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market_share', models.CharField(choices=[('Dominant', 'Dominant'), ('Average', 'Average'), ('weak', 'weak')], max_length=100)),
                ('score', models.PositiveIntegerField()),
                ('description', models.TextField()),
            ],
        ),
    ]
