# Generated by Django 4.0.10 on 2023-08-28 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0003_businessriskparameter_marketriskparameter'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagemementSuccessionRiskParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('management_succession', models.CharField(choices=[('ready succession', 'ready succession'), ('succession in question', 'succession in question')], max_length=100)),
                ('score', models.PositiveIntegerField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ManagementExperienceRiskParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('management_experience', models.CharField(choices=[('if 51% and above of top management have more than 10 years experience', 'if 51% and above of top management have more than 10 years experience'), ('if 51% and above of top management have more than 7 years experience', 'if 51% and above of top management have more than 7 years experience'), ('if 51% and above of top management have more than 3 years experience', 'if 51% and above of top management have more than 3 years experience'), ('if 51% and above of top management have less than 3 years experience', 'if 51% and above of top management have less than 3 years experience')], max_length=100)),
                ('score', models.PositiveIntegerField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ManagementQualificationRiskParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('management_qualification', models.CharField(choices=[('if 51% and above of top management are degree holders and above', 'if 51% and above of top management are degree holders and above'), ('if 51% and above of top management are diploma, degree and above holders', 'if 51% and above of top management are diploma, degree and above holders'), ('if 51% and above of top management are High School, diploma, degree and above holders', 'if 51% and above of top management are High School, diploma, degree and above holders'), ('if 51% and above of top management are below high school graduate', 'if 51% and above of top management are below high school graduate')], max_length=100)),
                ('score', models.PositiveIntegerField()),
                ('description', models.TextField()),
            ],
        ),
    ]
