# Generated by Django 4.0.10 on 2023-08-29 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0004_managemementsuccessionriskparameter_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrityOfCustomerRiskParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Integrity_risk', models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], max_length=100)),
                ('score', models.PositiveIntegerField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='LengthOfBorrowingRelationshipRiskParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrowing_length', models.CharField(choices=[('greater than 10 years', 'greater than 10 years'), ('5-9 years', '5-9 years'), ('2-4 years', '2-4 years'), ('1-2 years', '1-2 years'), ('less than 1 year', 'less than 1 year')], max_length=100)),
                ('score', models.PositiveIntegerField()),
                ('description', models.TextField()),
            ],
        ),
    ]
