# Generated by Django 4.0.10 on 2023-08-30 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0005_integrityofcustomerriskparameter_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OverdraftSwingHighestDebtRiskParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('highest_debt', models.CharField(choices=[('greater than 85%', 'greater than 85%'), ('60-84.9%', '60-84.9%'), ('less than 60%', 'less than 60%')], max_length=100)),
                ('score', models.PositiveIntegerField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='OverdraftSwingLowestDebtRiskParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lowest_debt', models.CharField(choices=[('at least credit balance within three month', 'at least credit balance within three month'), ('at least credit balance within six month', 'at least credit balance within six month'), ('at least 4% debt balance with a year', 'at least 4% debt balance with a year')], max_length=100)),
                ('score', models.PositiveIntegerField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='OverdraftTurnoverRiskParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overdraft_turnover', models.CharField(choices=[('greater than 3 times', 'greater than 3 times'), ('2-3 times', '2-3 times'), ('1-1.99 times', '1-1.99 times'), ('less than 1 times', 'less than 1 times')], max_length=100)),
                ('score', models.PositiveIntegerField()),
                ('description', models.TextField()),
            ],
        ),
    ]
