# Generated by Django 4.0.10 on 2023-08-31 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0007_termloancurrentriskparameter_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LcFacilitySettlementRiskParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('settled_lc', models.CharField(choices=[('settled within  a week', 'settled within  a week'), ('settled within  three weeks', 'settled within  three weeks'), ('settled within a month', 'settled within a month'), ('settled after a month', 'settled after a month')], max_length=100)),
                ('score', models.PositiveIntegerField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='LcFacilityTurnoverRiskParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lc_turnover', models.CharField(choices=[('settled with regular repayments', 'settled with regular repayments'), ('settled timely but with an elemwnt of irregularity', 'settled timely but with an elemwnt of irregularity'), ('settled within thirty days after due date', 'settled within thirty days after due date'), ('settled between 30 to 89 days after due date', 'settled between 30 to 89 days after due date'), ('settled after NPL or legal action', 'settled after NPL or legal action')], max_length=100)),
                ('score', models.PositiveIntegerField()),
                ('description', models.TextField()),
            ],
        ),
    ]
