# Generated by Django 4.0.10 on 2023-09-01 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0008_lcfacilitysettlementriskparameter_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MerchandiseLoanTurnoverRiskParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('merchandise_turnover', models.CharField(choices=[('greater than 2 times', 'greater than 2 times'), ('1.25-1.99 times', '1.25-1.99 times'), ('0.5-1.24 times', '0.5-1.24 times'), ('less than 0.5 times', 'less than 0.5 times')], max_length=100)),
                ('score', models.PositiveIntegerField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MerchandiseSettlementRiskParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('settled_ml', models.CharField(choices=[('settled all advances within 90 days', 'settled all advances within 90 days'), ('settled all advances within 120 days', 'settled all advances within 120 days'), ('settled within 145 days', 'settled within 145 days'), ('settled after 145 days', 'settled after 145 days')], max_length=100)),
                ('score', models.PositiveIntegerField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='lcfacilityturnoverriskparameter',
            name='lc_turnover',
            field=models.CharField(choices=[('greater than 3 times', 'greater than 3 times'), ('2-3 times', '2-3 times'), ('1-1.99 times', '1-1.99 times'), ('less than 1 times', 'less than 1 times')], max_length=100),
        ),
    ]
