# Generated by Django 4.0.10 on 2023-09-02 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0009_merchandiseloanturnoverriskparameter_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PSEForCoffeeSeasameTurnoverRiskParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pse_coffee_turnover', models.CharField(choices=[('greater than 2.5 times', 'greater than 2.5 times'), ('2-2.5 times', '2-2.5 times'), ('1.5-2 times', '1.5-2 times'), ('1-1.5 times', '1-1.5 times'), ('0.75-1 times', '0.75-1 times'), ('less than 0.75 times', 'less than 0.75 times')], max_length=100)),
                ('score', models.PositiveIntegerField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PSEForLeathermfgTurnoverRiskParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pse_leather_turnover', models.CharField(choices=[('greater than 2 times', 'greater than 2 times'), ('1.5-2 times', '1.5-2 times'), ('1.25-1.5 times', '1.25-1.5 times'), ('1-1.25 times', '1-1.25 times'), ('0.5-1 times', '0.5-1 times'), ('less than 0.5 times', 'less than 0.5 times')], max_length=100)),
                ('score', models.PositiveIntegerField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PSEForOtherTradingTurnoverRiskParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pse_other_turnover', models.CharField(choices=[('greater than 2.75 times', 'greater than 2.75 times'), ('2-2.75 times', '2.2.75 times'), ('1.5-2 times', '1.5-2 times'), ('1-1.5 times', '1-1.5 times'), ('0.75-1 times', '0.75-1 times'), ('less than 0.75 times', 'less than 0.75 times')], max_length=100)),
                ('score', models.PositiveIntegerField()),
                ('description', models.TextField()),
            ],
        ),
    ]
