# Generated by Django 4.0.10 on 2023-09-02 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rating', '0010_pseforcoffeeseasameturnoverriskparameter_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LetterOfGuaranteeSettlementRiskParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lg_settlement', models.CharField(choices=[('settled/expired without claim', 'settled/expired without claim'), ('settled/expired after claim', 'settled/expired after claim')], max_length=100)),
                ('score', models.PositiveIntegerField()),
                ('description', models.TextField()),
            ],
        ),
    ]
