# Generated by Django 4.0.10 on 2023-08-19 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('maker', 'Maker'), ('checker', 'Checker'), ('staff', 'staff')], default='maker', max_length=10),
        ),
    ]
